##### 其他資料清理
> 去除重複: df.drop_duplicates()
> 分組   : pd.cut

##### 完整實例
>

In [3]:
#!pip install yfinance
import pandas as pd
import yfinance as yf

df_quote = yf.download("1101.TW",start="2020-01-01", end="2022-11-30")
df_quote.tail()
df_quote_new =df_quote.resample("M").mean()
df_quote_new

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2020-01-31,37.880681,38.111573,37.695967,37.941290,32.555621,2.314452e+07
2020-02-29,36.864453,37.213069,36.725462,37.001165,31.748944,1.667600e+07
2020-03-31,34.352366,34.808902,33.858441,34.338591,29.464317,2.583771e+07
2020-04-30,35.778845,36.097042,35.568877,35.869758,30.778138,1.581025e+07
2020-05-31,36.962885,37.226968,36.772400,36.995355,31.743959,1.660900e+07
2020-06-30,37.354680,37.532178,37.166359,37.337363,32.037421,1.757845e+07
2020-07-31,38.763465,39.045806,38.573356,38.834991,33.322464,2.116630e+07
2020-08-31,39.651630,39.980242,39.313225,39.643692,35.365919,3.075036e+07
2020-09-30,38.328946,38.504577,38.027273,38.256627,34.790867,1.855571e+07
2020-10-31,37.038300,37.198598,36.830153,36.961740,33.613287,1.064124e+07
2020-11-30,38.307693,38.500346,38.119369,38.325010,34.853055,1.660278e+07
2020-12-31,39.192279,39.387944,39.022307,39.184373,35.634567,1.466547e+07
2021-01-31,38.113849,38.275223,37.891107,37.991113,34.549407,2.276422e+07
2021-02-28,37.673785,37.929046,37.484961,37.712249,34.295806,2.195340e+07
2021-03-31,39.967482,40.130716,39.717466,39.938554,36.320425,2.756885e+07
2021-04-30,45.525696,46.235338,44.843833,45.525696,41.401413,6.315975e+07
2021-05-31,46.139373,46.866693,45.344948,46.167513,41.985086,4.442555e+07
2021-06-30,46.665381,46.881845,46.379648,46.691357,42.461475,1.607629e+07
2021-07-31,47.213823,47.482435,46.891487,47.209690,42.932851,2.521782e+07
2021-08-31,44.771515,45.102115,44.339668,44.804575,42.503008,2.778035e+07
2021-09-30,45.282498,45.730254,44.964295,45.462055,44.260874,1.898831e+07
2021-10-31,45.055211,45.259770,44.705188,44.934749,43.747501,1.480724e+07
2021-11-30,43.707395,43.874762,43.457379,43.657805,42.504296,1.488653e+07
2021-12-31,43.011069,43.238357,42.837504,43.060659,41.922927,1.092872e+07
2022-01-31,43.111397,43.257872,42.871483,43.106347,41.967408,1.109078e+07
2022-02-28,42.902798,43.136146,42.714906,43.039170,41.902006,1.074571e+07
2022-03-31,44.030539,44.240039,43.838827,44.119478,42.953770,1.359781e+07
2022-04-30,43.390389,43.543509,42.988449,43.182242,42.041298,1.834100e+07
2022-05-31,38.855347,39.097787,38.537145,38.731963,37.708602,2.475314e+07
2022-06-30,36.866040,37.004577,36.560826,36.656070,35.687558,2.023756e+07
2022-07-31,37.482137,37.769814,37.164372,37.476509,36.821245,2.018867e+07
2022-08-31,39.204348,39.391304,38.936956,39.258695,39.258695,1.409493e+07
2022-09-30,38.145238,38.345238,37.809524,37.995238,37.995238,2.869266e+07
2022-10-31,32.362500,32.580000,31.922500,32.092500,32.092500,2.634033e+07
2022-11-30,32.250000,32.659524,31.985714,32.404762,32.404762,3.009818e+07

In [4]:
df_monthly_sales = pd.read_csv("./stock_monthly_sales.csv")
df_monthly_sales.head()

   公司代碼      年月     單月營收  單月月增率  單月年增率       累計營收  累計年增率      盈餘 每股盈餘（元）
0  1101  202211   9674.6  -14.9   -0.8  100384.63    4.3      --      --
1  1101  202210  11368.1    9.3   18.9   90710.06    4.9      --      --
2  1101  202209  10404.9   -2.7    8.4   79274.33    3.1  2917.8    0.38
3  1101  202208  10689.9    5.8   19.3   68937.06    2.4  2917.8    0.38
4  1101  202207  10102.5   10.5   21.4   58247.20   -0.2  2917.8    0.38

In [7]:
#利用日期join兩個表格
df_quote_new = df_quote.reset_index()
df_quote_new.Date = df_quote_new.Date
df_quote_new.Date = df_quote_new.Date.map(lambda x:str(x)[:4]+str(x)[5:7])
df_quote_new
df_monthly_sales["年月"] = df_monthly_sales["年月"].astype('str')
df = pd.merge(left=df_monthly_sales, right=df_quote_new,left_on="年月",right_on="Date",how="inner")
df_new = df[["Date","單月營收","Adj Close"]]
#欄位改名
df_new.rename({'單月營收':"sales"},axis=1,inplace=True)
df_new

,公司代碼,年月,單月營收,單月月增率,單月年增率,累計營收,累計年增率,盈餘,每股盈餘（元）,Date,Open,High,Low,Close,Adj Close,Volume
0,1101,202211,9674.6,-14.9,-0.8,100384.63,4.3,--,--,202211,30.250000,30.750000,30.100000,30.650000,30.650000,12092559
1,1101,202211,9674.6,-14.9,-0.8,100384.63,4.3,--,--,202211,30.650000,30.850000,30.549999,30.750000,30.750000,11682846
2,1101,202211,9674.6,-14.9,-0.8,100384.63,4.3,--,--,202211,30.250000,30.400000,30.150000,30.299999,30.299999,16984572
3,1101,202211,9674.6,-14.9,-0.8,100384.63,4.3,--,--,202211,30.200001,30.549999,30.150000,30.450001,30.450001,15739518
4,1101,202211,9674.6,-14.9,-0.8,100384.63,4.3,--,--,202211,30.600000,31.000000,30.500000,31.000000,31.000000,16539214
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
706,1101,202001,7502.1,-39.3,-20.1,7502.14,-20.1,2999.8,0.52,202001,38.530064,38.919693,38.486771,38.746525,33.246555,17110414
707,1101,202001,7502.1,-39.3,-20.1,7502.14,-20.1,2999.8,0.52,202001,38.876404,38.876404,38.659939,38.876404,33.357998,10890829
708,1101,202001,7502.1,-39.3,-20.1,7502.14,-20.1,2999.8,0.52,202001,38.919693,38.962986,38.833111,38.919693,33.395142,10244649
709,1101,202001,7502.1,-39.3,-20.1,7502.14,-20.1,2999.8,0.52,202001,36.971542,37.274590,36.019115,36.235577,31.092031,74090372
710,1101,202001,7502.1,-39.3,-20.1,7502.14,-20.1,2999.8,0.52,202001,36.148991,36.798374,36.148991,36.408745,31.240616,30525307